import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Insani | Web Developer",
  description: "Generated by Arcshin",
  icons: {
<<<<<<< HEAD
    icon: './assets/img/insani.png', // Ini akan mengarah ke public/assets/img/insani.png
=======
    icon: '/assets/img/icon.png', // Ini akan mengarah ke public/assets/img/insani.png
>>>>>>> bb8fe0ac75828e717dfdc30c8211ea8c185e914b
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
